[package]
name = "optical-music-recognition"
version = "0.1.0"
authors = ["Mitchell Metcalfe <mitchell.s.metcalfe@gmail.com>"]

[dependencies]
libc = "0.2"

# ffmpeg-sys = "2.8.6-1" # Problems due to bad config detection.
[dependencies.ffmpeg-sys]
git = "file:/Users/mitchell/code/rust-ffmpeg-sys"
